export default {
  "login": "GIGGSI",
  "id": 18408857,
  "node_id": "MDQ6VXNlcjE4NDA4ODU3",
  "avatar_url": "https://avatars.githubusercontent.com/u/18408857?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/GIGGSI",
  "html_url": "https://github.com/GIGGSI",
  "followers_url": "https://api.github.com/users/GIGGSI/followers",
  "following_url": "https://api.github.com/users/GIGGSI/following{/other_user}",
  "gists_url": "https://api.github.com/users/GIGGSI/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/GIGGSI/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/GIGGSI/subscriptions",
  "organizations_url": "https://api.github.com/users/GIGGSI/orgs",
  "repos_url": "https://api.github.com/users/GIGGSI/repos",
  "events_url": "https://api.github.com/users/GIGGSI/events{/privacy}",
  "received_events_url": "https://api.github.com/users/GIGGSI/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Stoyan Spasov",
  "company": null,
  "blog": "https://sto-portfolio.netlify.app/",
  "location": "Blagoevgrad",
  "email": null,
  "hireable": null,
  "bio": "Highly motivated, proactive team player who feels comfortable in dynamic atmosphere, I am eager to contribute towards building a healthy work environment and be",
  "twitter_username": 'StoyanSpasov',
  "public_repos": 17,
  "public_gists": 10,
  "followers": 1,
  "following": 3,
  "created_at": "2016-04-11T23:28:54Z",
  "updated_at": "2021-04-12T16:27:21Z"
}